# Generated by Django 5.2.6 on 2026-07-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty preset selected for this run.', max_length=10),
        ),
        migrations.AddField(
            model_name='score',
            name='distance',
            field=models.IntegerField(default=0, help_text='Total distance (metres) the player survived.'),
        ),
    ]
